spring:
  datasource:
#    url: jdbc:mysql://39.106.7.57:3306/ais?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/ais?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: MySQL
#    database-platform: com.demo2.demo.config.MysqlConfig
    show-sql: true

    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

